<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<OutputType>WinExe</OutputType>

		<TargetFramework>net10.0-windows</TargetFramework>

		<Nullable>enable</Nullable>

		<ImplicitUsings>enable</ImplicitUsings>

		<UseWPF>true</UseWPF>

		<UseWindowsForms>true</UseWindowsForms>

		<!-- Rider「surface/heuristic」单独编译当前工程时，默认必须为 true，否则会 CS0006 找不到依赖 DLL -->

		<BuildProjectReferences>true</BuildProjectReferences>

	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Assets\window_bg.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\overlay_animations\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>

		<ProjectReference Include="..\AL1_S_Terminal.Win32\AL1_S_Terminal.Win32.csproj" />

	</ItemGroup>

</Project>

